version: '2'
services:
  deluge:
    container_name: deluge
    image: binhex/arch-delugevpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_ENABLED=yes
      - VPN_USER
      - VPN_PASS
      - VPN_PROV=custom
      - LAN_NETWORK=10.0.0.0/24
      - DEBUG=false
    volumes:
      - ${HOME}/services/deluge/data:/data
      - ${HOME}/services/deluge/config:/config
      - /etc/localtime:/etc/localtime:ro
     
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=EST
      - ADVERTISE_IP=http://10.0.0.113:32400/
    volumes:
      - ${HOME}/services/plex/config:/config
      - ${HOME}/services/plex/transcode:/transcode
      - ${HOME}/services/plex/data:/data
  
  sonnar:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - TZ=EST
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/services/sonarr/config:/config
      - ${HOME}/services/plex/data/TV:/tv
      - ${HOME}/services/downloads:/downloads

  bind:
    container_name: bind
    image: sameersbn/bind
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - WEBMIN_ENABLED=false
    volumes:
      - ${HOME}/services/bind:/data 
